server:
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8081
spring:
  application:
    name: api-music
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev
    username: usr-spotify
    password: pwd-spotify
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true